// Generated by scripts/generate_control_plane_contract.py. Do not edit.

export interface BackfillRequest {
  "pipeline_version_id": string
  "window_start": string
  "window_end": string
}

export interface BootstrapRequest {
  "organization_id": string
  "workspace_slug": string
  "workspace_name": string
}

export interface CommandResponse {
  "id": string
  "workspace_id": string
  "kind": string
  "resource_id": string | null
  "state": string
  "created_at": string
}

export interface ConnectionCreateRequest {
  "environment_id"?: string | null
  "name": string
  "connector_type": string
  "secret_reference": string
  "metadata"?: Record<string, unknown>
}

export interface ConnectionResponse {
  "id": string
  "workspace_id": string
  "environment_id": string | null
  "name": string
  "connector_type": string
  "metadata": Record<string, unknown>
  "has_secret_reference": boolean
  "created_at": string
  "updated_at": string
}

export interface HTTPValidationError {
  "detail"?: Array<ValidationError>
}

export interface PipelineCreateRequest {
  "pipeline_key": string
  "document": Record<string, unknown>
}

export interface PipelineResponse {
  "id": string
  "workspace_id": string
  "pipeline_key": string
  "config_digest": string
  "created_at": string
}

export interface PipelineValidationRequest {
  "document": Record<string, unknown>
}

export interface ProblemResponse {
  "type": string
  "title": string
  "status": number
  "detail": string
  "instance": string
  "request_id": string
}

export interface RunCreateRequest {
  "pipeline_version_id": string
}

export interface RunResponse {
  "id": string
  "workspace_id": string
  "pipeline_version_id": string
  "state": string
  "attempt": number
  "retry_category": string | null
  "cancel_requested": boolean
  "created_at": string
  "started_at": string | null
  "finished_at": string | null
  "parent_run_id": string | null
  "error": Record<string, unknown> | null
}

export interface ScheduleResponse {
  "id": string
  "workspace_id": string
  "pipeline_version_id": string
  "trigger_kind": string
  "trigger_spec": string
  "timezone": string
  "enabled": boolean
  "next_run_at": string
  "created_at": string
  "updated_at": string
}

export interface ScheduleUpsertRequest {
  "id": string
  "pipeline_version_id": string
  "trigger_kind": "cron" | "interval"
  "trigger_spec": string
  "timezone": string
  "enabled"?: boolean
  "next_run_at": string
}

export interface StoredEventResponse {
  "run_id": string
  "sequence": number
  "event_type": string
  "payload": Record<string, unknown>
  "occurred_at": string
}

export interface ValidationError {
  "loc": Array<string | number>
  "msg": string
  "type": string
  "input"?: unknown
  "ctx"?: Record<string, unknown>
}

export interface WorkspaceResponse {
  "id": string
  "organization_id": string
  "slug": string
  "name": string
  "role": "owner" | "admin" | "operator" | "viewer"
  "created_at": string
}
