"""Generate the versioned OpenAPI document and browser response types."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from loafer.adapters.metadata import SqlMetadataStore
from loafer.control_plane.app import ControlPlaneSettings, create_app
from loafer.control_plane.auth import StaticTokenVerifier

ROOT = Path(__file__).resolve().parents[1]
OPENAPI_PATH = ROOT / "openapi" / "control-plane-v1.json"
TYPES_PATH = ROOT / "web" / "src" / "lib" / "control-plane-types.generated.ts"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when checked-in contract artifacts are stale.",
    )
    args = parser.parse_args()

    schema = _openapi_schema()
    outputs = {
        OPENAPI_PATH: json.dumps(schema, indent=2, sort_keys=True) + "\n",
        TYPES_PATH: _typescript_types(schema),
    }
    stale = [
        path
        for path, content in outputs.items()
        if not path.exists() or path.read_text() != content
    ]
    if args.check:
        if stale:
            rendered = ", ".join(str(path.relative_to(ROOT)) for path in stale)
            parser.error(f"generated control-plane artifacts are stale: {rendered}")
        return
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def _openapi_schema() -> dict[str, Any]:
    store = SqlMetadataStore("sqlite://")
    try:
        store.migrate()
        app = create_app(
            settings=ControlPlaneSettings(
                issuer="https://auth.example.invalid",
                audience="https://api.example.invalid",
                jwks_url="https://auth.example.invalid/api/auth/jwks",
                allowed_origins=("https://app.example.invalid",),
            ),
            store=store,
            verifier=StaticTokenVerifier({}),
        )
        return app.openapi()
    finally:
        store.close()


def _typescript_types(openapi: dict[str, Any]) -> str:
    schemas = openapi["components"]["schemas"]
    lines = [
        "// Generated by scripts/generate_control_plane_contract.py. Do not edit.",
        "",
    ]
    for name, schema in sorted(schemas.items()):
        if schema.get("type") == "object" and "properties" in schema:
            lines.append(f"export interface {name} {{")
            required = set(schema.get("required", []))
            for property_name, property_schema in schema["properties"].items():
                optional = "" if property_name in required else "?"
                lines.append(
                    f"  {json.dumps(property_name)}{optional}: {_typescript_type(property_schema)}"
                )
            lines.append("}")
        else:
            lines.append(f"export type {name} = {_typescript_type(schema)}")
        lines.append("")
    return "\n".join(lines)


def _typescript_type(schema: dict[str, Any]) -> str:
    reference = schema.get("$ref")
    if reference:
        return reference.rsplit("/", 1)[-1]
    if "anyOf" in schema:
        choices = list(dict.fromkeys(_typescript_type(choice) for choice in schema["anyOf"]))
        return " | ".join(choices)
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    schema_type = schema.get("type")
    if schema_type == "array":
        return f"Array<{_typescript_type(schema.get('items', {}))}>"
    if schema_type == "object":
        properties = schema.get("properties")
        if properties:
            fields = [
                f"{json.dumps(name)}: {_typescript_type(value)}"
                for name, value in properties.items()
            ]
            return "{ " + "; ".join(fields) + " }"
        additional = schema.get("additionalProperties")
        value_type = _typescript_type(additional) if isinstance(additional, dict) else "unknown"
        return f"Record<string, {value_type}>"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "string":
        return "string"
    return "unknown"


if __name__ == "__main__":
    main()
