import React, { useState, useRef } from 'react';
import { ArrowUpRight, Info, AlertTriangle, Lightbulb, AlertOctagon, Copy, Check } from 'lucide-react';
import { cn } from '../../utils/cn';

export const MDXComponents = {
  h1: (props: any) => <h1 className="text-[30px] font-sans font-bold text-text-primary mt-0 mb-8 tracking-tight" {...props} />,
  h2: (props: any) => <h2 className="text-[20px] font-sans font-semibold text-text-primary mt-12 mb-4 pt-6 border-t border-border-subtle scroll-mt-[70px]" {...props} />,
  h3: (props: any) => <h3 className="text-[16px] font-sans font-semibold text-text-primary mt-8 mb-3 scroll-mt-[70px]" {...props} />,
  h4: (props: any) => <h4 className="text-[13px] font-sans font-semibold text-text-primary uppercase tracking-[0.06em] mt-6 mb-2 scroll-mt-[70px]" {...props} />,
  p: (props: any) => <p className="text-[14px] text-text-secondary leading-[1.75] mb-4" {...props} />,
  
  pre: (props: any) => {
    const [copied, setCopied] = useState(false);
    const preRef = useRef<HTMLPreElement>(null);
    
    // Detect if output
    const isOutput = props['data-language'] === 'text' || 
                    props['data-language'] === 'output' ||
                    props.title === 'Output';

    const onCopy = () => {
      if (preRef.current) {
        let text = preRef.current.innerText;
        const lang = props['data-language'];
        if (lang === 'bash' || lang === 'sh' || lang === 'shell' || lang === 'zsh') {
          text = text.split('\n')
            .map(line => line.replace(/^(\$|>)\s*/, ''))
            .join('\n');
        }
        navigator.clipboard.writeText(text.trim());
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }
    };

    return (
      <div className="relative group my-4 first:mt-0 last:mb-0">
        <pre 
          ref={preRef} 
          {...props} 
          className={cn(
            props.className, 
            "m-0 border-none bg-transparent overflow-x-auto",
            isOutput && "opacity-80"
          )} 
        />
        {!isOutput && (
          <button
            onClick={onCopy}
            className="absolute top-2 right-2 p-1.5 rounded-md bg-bg-surface/80 backdrop-blur-sm border border-border-default opacity-0 group-hover:opacity-100 transition-all hover:bg-bg-elevated hover:border-border-strong focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 shadow-sm z-10"
            title="Copy to clipboard"
          >
            {copied ? (
              <Check className="w-3.5 h-3.5 text-green-500" />
            ) : (
              <Copy className="w-3.5 h-3.5 text-text-muted" />
            )}
          </button>
        )}
        {isOutput && (
          <div className="absolute top-2 right-3 text-[10px] font-bold text-indigo-400 opacity-60 uppercase tracking-widest select-none pointer-events-none">
            Output
          </div>
        )}
      </div>
    );
  },
  
  a: (props: any) => {
    const isExternal = props.href?.startsWith('http');
    return (
      <a 
        className="text-indigo-400 no-underline hover:underline decoration-indigo-400/50 underline-offset-4 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 rounded-[2px]" 
        target={isExternal ? '_blank' : undefined}
        rel={isExternal ? 'noopener noreferrer' : undefined}
        {...props}
      >
        {props.children}
        {isExternal && <ArrowUpRight className="inline-block w-3 h-3 ml-0.5 relative -top-[1px] opacity-70" />}
      </a>
    );
  },
  
  ul: (props: any) => <ul className="list-disc pl-5 mb-6 text-[14px] text-text-secondary leading-[1.75] space-y-1" {...props} />,
  ol: (props: any) => <ol className="list-decimal pl-5 mb-6 text-[14px] text-text-secondary leading-[1.75] space-y-1" {...props} />,
  li: (props: any) => <li className="" {...props} />,
  
  table: (props: any) => (
    <div className="overflow-x-auto mb-8 rounded-md border border-border-subtle shadow-sm my-6 bg-bg-surface">
      <table className="w-full text-left border-collapse text-[13px] text-text-secondary" {...props} />
    </div>
  ),
  th: (props: any) => <th className="bg-bg-elevated px-4 py-2.5 border-b border-border-subtle font-medium text-text-primary whitespace-nowrap" {...props} />,
  td: (props: any) => <td className="px-4 py-2 border-b border-border-subtle/50" {...props} />,
  
  // Exclude style on code tags that are generated by shiki. Shiki wraps its spans inside pre > code.
  code: (props: any) => {
    if (props.className && props.className.includes('shiki')) {
      return <code {...props} />;
    }
    return (
      <code 
        className="font-mono text-[12px] bg-bg-elevated border border-border-subtle rounded-[3px] px-1.5 py-0.5 text-text-code" 
        {...props} 
      />
    );
  },
  
  // Custom Callout handling through standard blockquotes
  blockquote: (props: any) => {
    const rawText = props.children?.props?.children || '';
    const text = Array.isArray(rawText) ? rawText.join('') : typeof rawText === 'string' ? rawText : '';
    
    let type = 'info';
    let title = 'Note';
    let Icon = Info;
    
    if (text.startsWith('Warning:') || text.startsWith('[!WARNING]')) { type = 'warning'; title = 'Warning'; Icon = AlertTriangle; }
    else if (text.startsWith('Tip:') || text.startsWith('[!TIP]')) { type = 'tip'; title = 'Tip'; Icon = Lightbulb; }
    else if (text.startsWith('Danger:') || text.startsWith('[!DANGER]')) { type = 'danger'; title = 'Danger'; Icon = AlertOctagon; }
    
    const borders = {
      info: 'border-l-blue-500/80',
      warning: 'border-l-amber-500/80',
      tip: 'border-l-green-500/80',
      danger: 'border-l-red-500/80'
    };
    
    const bg = {
      info: 'bg-blue-900/10',
      warning: 'bg-amber-900/10',
      tip: 'bg-green-900/10',
      danger: 'bg-red-900/10'
    };

    const textColors = {
      info: 'text-blue-400',
      warning: 'text-amber-400',
      tip: 'text-green-400',
      danger: 'text-red-400'
    };

    // Remove the prefix text
    const cleanChildren = React.Children.map(props.children, child => {
      if (!child || !child.props || !child.props.children) return child;
      let childText = child.props.children;
      if (typeof childText === 'string') {
        childText = childText.replace(/^(Warning:|Tip:|Danger:|Note:|\[!(WARNING|TIP|DANGER|NOTE)\])\s*/i, '');
      } else if (Array.isArray(childText)) {
        if (typeof childText[0] === 'string') {
          const newArr = [...childText];
          newArr[0] = newArr[0].replace(/^(Warning:|Tip:|Danger:|Note:|\[!(WARNING|TIP|DANGER|NOTE)\])\s*/i, '');
          childText = newArr;
        }
      }
      return React.cloneElement(child, { children: childText });
    });

    return (
      <div className={cn("my-6 p-4 rounded-sm border-l-[3px] border border-border-subtle", borders[type as keyof typeof borders], bg[type as keyof typeof borders])}>
        <div className={cn("flex items-center gap-2 mb-2 font-medium text-[13px] uppercase tracking-wide", textColors[type as keyof typeof textColors])}>
          <Icon className="w-4 h-4" />
          {title}
        </div>
        <div className="text-[14px] text-text-secondary leading-[1.6]">
          {cleanChildren}
        </div>
      </div>
    );
  }
};
